[package]
name = "vignette-core"
version = "0.1.0"
edition = "2024"

[features]
default = ["async-hid"]
async-hid = ["dep:async-hid"]

[dependencies]
async-hid = { version = "0.5.3", default-features = false, features = ["tokio", "win32"], optional = true }
async-trait = "0.1.92"
binrw = "0.15.2"
futures = "0.3.34"
tokio = { workspace = true }
